large numbers converted to k notation
Project-Skill-Tree/Skill-Tree-Discord-Bot pull request #112
Opened 2022-09-02 17:39 UTC by Gamsti1337

**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**

**Semantic versioning classification:**

- [ yes ] This PR changes the framework's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

In this PR I coded a function to change large numbers to a K notation (69420 = 69.4k) and removed duplicate stats on /bot command (like servers and total servers) #103

Some change influenced by discord is there like:
> putting the deploy command functionality in ready.js. Why? Because when trying to setup I needed to /deploy to show all slash commands... but I didn't have any slash commands to use /deploy

2022-09-02 17:43 UTC, OmerSabic approved these changes
lgtm

2022-09-02 17:48 UTC, Gamsti1337 commented
@OmerSabic can you merge?

2022-09-02 17:50 UTC, OmerSabic commented
> @OmerSabic can you merge?

I don't have the permissions to

2022-09-02 17:50 UTC, Gamsti1337 commented
lets wait for sean

2022-09-02 18:01 UTC, Gamsti1337 commented
@Project-Skill-Tree/management can you merge?

2022-09-02 18:19 UTC, swatarianess requested changes

2022-09-02 18:19 UTC, swatarianess commented on .env.example
> -API_URL=
Don't delete this file, its needed 😉

2022-09-02 18:40 UTC, seanjhardy requested changes
Fix the units of number formatter, and make sure it actually returns a value for every input (will fail for 900-999)

2022-09-02 18:40 UTC, seanjhardy commented
Smh omer look more thoroughly

2022-09-03 08:03 UTC, Gamsti1337 commented
rewrote the function, can you check now?

2022-09-03 09:54 UTC, seanjhardy approved these changes

2022-09-03 10:27 UTC, OmerSabic commented
> Smh omer look more thoroughly

yep my bad, gonna check better from now on

2022-09-03 11:34 UTC, swatarianess approved these changes

2022-09-03 11:39 UTC, merged