Potential fix for cron error
Project-Skill-Tree/Skill-Tree-Discord-Bot pull request #83
Opened 2022-07-14 11:46 UTC by iJynx

**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**
This is a potential fix to #82 

I reviewed the cron  config and found a potential error in it. I removed the date checking code and replaced it with some that changes the cron time to GMT + 12 and then checks every hour from sunday 12AM to Monday 12AM. This will make sure that it runs at every possible hour on Sunday.

**Semantic versioning classification:**
???

- [ ] This PR changes the framework's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

2022-07-15 00:12 UTC, seanjhardy requested changes
Uhh sorry I don't see how this can work, where is the offset?? Is this actually getting the correct users in the correct timezone, because timezones don't go from -12 to +12, they go from like -14 to +12, and what if we want to change the day it happens? Or the hour?? How does it happen at 6PM in the user's local time, offset isn't even used?

2022-07-15 02:55 UTC, iJynx commented
I wrote a complete overhaul of the weekly report code and I do concede that this code might be slightly confronting to review so I'll just add an explanation of my most recent commit.

1. First I make the `cron` job run at every 30 minutes.
2. Next I get the GMT offset of the bot (difference between the bot's time and GMT+8 time)
3. I use that offset to find GMT+0, and with that I can find GMT+12 (which is rounded to the nearest 30'th minute to account for millisecond delays in the code execution)
4. I check that the current GMT+12 time is between Sunday 6PM and Monday 8PM (This will make sure that the code in this if statement will run at every possible time from GMT+12 to GMT-14 [the difference of which is 26 hours which has been accounted for by checking between Sunday 6pm and Monday 8pm, as when it's Monday 8pm for GMT+12 it's Sunday 6pm for GMT-14])
5. I get the absolute time for the last Sunday 6PM relative to GMT+12
6. I compare that absolute time to the current time to get the variable `difference` which represents the difference in hours between current time and last Sunday 6pm
7. Then this difference is used to find the offset which GMT time zone is currently 6pm. For example if it's 10PM for GMT+12 then it's been 4 hours since 6pm. 12 - 4 = 8 which tells you that at GMT+8 it must be 6pm. Then this is used as the offset to query the backend API to search for all users at GMT+8.
8. ...
9. profit

2022-07-27 03:50 UTC, swatarianess approved these changes

2022-08-03 14:53 UTC, closed without merging

2022-08-03 14:55 UTC, seanjhardy commented
Added to the bug_fixes branch so that I could deploy the full working weekly report code without waiting for the branches to merge 👍